### ISSUE TITLE
Tag images with docker version

### ISSUE THREAD

**Issue by j-san** [blueimp/buildkite-agent#1]
It would be nice if images are tagged with the docker version. I need Docker 1.8 to works with Tutum but i can't install previous version :cry:.

**Comment by j-san** [comment]
btw, very nice work, thanks :)

**Comment by blueimp** [comment]
Thanks for the recommendation, it was something I wanted to do for a while.

You can now use the following tagged versions:

* blueimp/buildkite-agent:dind-1.7
* blueimp/buildkite-agent:dind-1.8
* blueimp/buildkite-agent:dind-1.9

**Comment by j-san** [comment]
Thanks !! 
:D
